### ISSUE TITLE
Loss of case sensitivity with INCLUDE

### ISSUE THREAD

**Issue by mougino** [RFO-BASIC/Basic#177]
As spotted here: http://rfobasic.freeforums.org/post16859.html#p16859

BASIC! converts the `INCLUDE` instruction to lower case: the keyword (normal) but also the rest of the line, including the include-file name (not normal).
I think the reason is because the argument after the `INCLUDE` is not protected by double quotes so it is lowered as well. I looked for the `INCLUDE` code in Run.java but could not find it, if you point me to it I'll be happy to help fixing.

The lower case is problematic for my lib "GW.bas": BASIC! looks in fact for "gw.bas", not "GW.bas".
This doesn't create any bug in the editor, where the /sdcard file-system is FAT (case insensitive) but it does bug in an APK where the /assets file-system is case sensitive, `INCLUDE GW.bas` throws a `error_include_file(gw.bas) not found` even if the file is there.

**Comment by jMarcS** [comment]
`INCLUDE` is handled in `AddProgramLine.java`, while the program file is being loaded. That's why the manual says "The program is not yet running, therefore the path cannot be a string expression."

`AddProgramLine.java.doInclude(String fileName)` has this line:
`fileName = fileName.substring(kw_include.length()).trim();`
If the program line is `include fred.bas`, this sets `fileName` to `fred.bas`. Notice there is nothing there to force case. That's because it has already been done. `doInclude(String)` is called from `AddLine(String)`, after `AddLine` has forced unquoted characters to lower-case. If the original line was `INCLUDE Fred.BAS`, then `doInclude` sees `include fred.bas`.

However, if the original line was `INCLUDE "Fred.BAS"`, the quotes protect the case from `AddLine`. Then `doInclude` sees `include "Fred.BAS"`. So all that is needed to fix `doInclude` is to add the line:
`fileName = fileName.replace("\"", "")`
to remove all quotes. Yes, that's a little casual -- it will remove ALL quotes, but file names should not have quotes, so it should be ok.

Digression: the `replace` as written would allow the user to write `INCLUDE "Fred.BAS` with no closing quote, but `AddLine` already allows that case. If it sees end-of-line while in a quoted string, it adds a closing quote. So if the original line is `INCLUDE "Fred.BAS`, then `doInclude` sees `include "Fred.BAS"`. That's why you can write
`PRINT "Hello, BASIC!`
and it works.

But wait! There's more! I'll comment on error-handling in the next post.

**Comment by jMarcS** [comment]
The change above preserves file name case, so you can correctly match the case of a "file" in _assets_, but what if the file does not exist? `doInclude` is supposed to put an error message in the calling .bas file, where it would have put the included program lines if the file had existed. It does that by building an error message and (recursively) calling `AddLine` -- the error message causes a syntax error when the program runs. Since the quotes have been removed,  `AddLine` forces the file name to lower-case in the error message! This does not help the user much.

A better change keeps two copies of the file name: one without the quotes, for doing file operations, and one with the quotes, for generating error messages.

But wait! There's STILL more! There's a bug in the error-handling. See next post.

**Comment by jMarcS** [comment]
I tried to test this by giving INCLUDE the name of a file that does not exist, expecting an error message. BASIC! crashed with a null-pointer exception.

Nicolas, has somebody reported that a bad INCLUDE crashes BASIC!? I don't remember seeing it. Is that just one of those things that "every BASIC! programmer knows"?

Anyway, fixing it requires another change in `AddProgramLine.java.doInclude(String)`. As written, it relies on getting an exception from `Basic.getBufferedReader(String, String)` if the file (or asset) is not found. However, that method does not throw an exception if the SD card file does not exist. It just returns `null`. (That may be a fairly recent change, which might explain why I have heard no complaints.)

The fix is to check for a null pointer reference, to cover the case where there is no exception.

All of the changes I've described are in `AddProgramLine.java`, which I'll commit to GitHub in a few minutes.

**Comment by jMarcS** [comment]
I forgot to explain what the user program actually has to do to make this work.

`INCLUDE FileName.bas` will actually try to load `filename.bas`.

`INCLUDE "FileName.bas"` will actually try to load `FileName.bas`. If the file `filename.bas` (or `FILENAME.BAS`, or any other variant) exists on the SD card in the `data` directory, `INCLUDE` will load that file. But if no such file exists on the SD card, `INCLUDE` will try to load the _assets_ "file" `FileName.bas`. The case must match exactly: `assets/<path>/data/filename.bas` will not be loaded.

I'll update the manual to say that (or something like that).

**Comment by jMarcS** [comment]
Ach! Typo in the commit comment. I did the commit, but I typed the issue number wrong, so there was no notification here. Sorry...

**Comment by mougino** [comment]
Thanks for all the precisions above Marc, very informational as always.
I also came to the conclusion that in order to protect an `INCLUDE` of a non-lower case file name in an APK you need to put the name between double quotes, that seems the easiest tip to give a programmer. Thanks for your correction!

**Comment by jMarcS** [comment]
Released in v01.85, 2015/02/15.
