### ISSUE TITLE
Enable graphics acceleration at runtime

### ISSUE THREAD

**Issue by mougino** [RFO-BASIC/Basic#190]
Following Sanjay's request at http://rfobasic.freeforums.org/hardware-acceleration-t3430.html

I was able to find the good method to selectively enable/disable hardware acceleration on a view (so we can disable HW accel by default, and then it is the user's responsibility if he chooses to enable it to check it doesn't break his drawing routines).

As a first step I implemented method `GR.ACCEL 0|1` in **Run.java** (we can in a second step implement `HTML.ACCEL 0|1` if we decide so, I'm in favour of having it always activated but we can discuss about it).

Since HW accel needs API 11, I needed to call `GR.drawView.setLayerType()` via reflection. Ok I did.

But then the method throws an `InvocationTargetException` with the following detail: `CalledFromWrongThreadException : Only the original thread that created a view hierarchy can touch its views`

I am not fluent enough in BASIC! architecture, Marc do you have an idea why this error occurs and how to fix it? (I'm guessing moving the `GR.drawView.setLayerType()` at another place... but where??)

**Comment by mougino** [comment]
I might have found a clue here: http://stackoverflow.com/questions/5161951/android-only-the-original-thread-that-created-a-view-hierarchy-can-touch-its-vi

I just have to see how to make it work in my case (some problem dealing with Exceptions and returned boolean...)

**Comment by jMarcS** [comment]
I'm not sure what you're doing with reflection; I'd have to see your code. The API level is stored as a constant. You can get it like this: `int level = Build.VERSION.SDK_INT;`

Thanks for finding `setLayerType()`. I didn't know where to start. Now I have some reading to do.

You need to invoke `setLayerType()` on the `DrawView` while the `GR` Activity is running. It can be in or out of the the `DrawView` class itself, but it has to be in `GR`. Somehow, the interpreter in the background thread has to tell either `GR` or `GR.DrawView` what to do.

- Right now, the interpreter usually talks to the `DrawView` by putting things in the Display List. Look at `GR.open`.
- Also, the `GR` Activity holds a static reference to the `DrawView`. That's probably not a good idea, but it is convenient sometimes.  Look at `GR.orientation`. 
- It's common to send messages to an Activity using its `Looper`, but so far we have not done that in `GR`. The static reference is more direct.

Can we use a preferences option instead of a command to change accel? That way there is no communication needed from the interpreter. The `GR.onOpen()` or `GR.onResume()` would read the Preference and set the layer type for the duration of graphics mode. Eventually we will want to find out what happens if the type is changed between `GR.render` commands, but may not for the first trial :{)}

**Comment by mougino** [comment]
I will do as you suggest: add a preference option instead of a command. But we have to remember that it will be tedious for a user to switch from hw accel to sw accel. And he might want to do that by command if, let's say, he is working on 2 programs, one needing hw accel, the other one not supporting it (typically if it uses Gr.Screen.To_Bitmap)

**Comment by mougino** [comment]
After several attempts, I think that the preference is the good way to go.
Because `setLayerType` only works once so you cannot revert from accel off to accel on during a same graphic session. So it's better to set the accel option when opening graphics, like you said.

I successfully created an option in the menu, and tried a nice animation demo I previously did that uses large bitmaps, with graphic acceleration checked and unchecked. The results are 24 fps for sw accel and 52 fps for hw accel.

Do you want me to send you the code and demo ?

**Comment by mougino** [comment]
Marc, I committed to my own repo mougino/Basic: see a024ce53452a2e6f096b9cea09d71ae0de49665c

I let you pull from my repo to yours and push to RFO-BASIC/Basic if you feel like it.

**Comment by jMarcS** [comment]
I have pulled it down. Looks great!

As a quick test, I ran Gilles' floodfill demo program. Not only does it work, but it works faster, even though it's almost all bitmap.

I made one change to your code. As I understand it, setting the view layer type does not turn hw accel on or off. It only enables or disables use of hw accel if it is turned on. So I added a line in the `DrawView` constructor to check if hw accel is enabled in the manifest, as shown [here](http://developer.android.com/guide/topics/graphics/hardware-accel.html#determining). This prevents setting `LAYER_TYPE_HARDWARE` if hw accel is off.

I don't see anything in the `setLayertype()` code that looks like it requires this check, but I figure it's good defensive programming. Please tell me if I've got this wrong!

Here is the modified code:

	if ((android.os.Build.VERSION.SDK_INT >= 11) &&	// Hardware acceleration is supported starting API 11
		isHardwareAccelerated())					// may be enabled or disabled in Manifest
	{
		// Hardware acceleration is enabled for the app.
		// Choose whether to use it in DrawView based on user Preference.
		int layerType = Settings.getGraphicAcceleration(context)
					? View.LAYER_TYPE_HARDWARE	// use hardware acceleration
					: View.LAYER_TYPE_SOFTWARE;	// disable hardware acceleration
		setLayerType(layerType, null);
	}

**Comment by mougino** [comment]
Seems good to me. I don't know what enbaling hardware accel does when application/acivity doesn't have it on, but you're right let's stay defensive.

**Comment by jMarcS** [comment]
Gah... I forgot to reference this issue in the commit comment. Sorry.

Now that it's committed, I realized I/we forgot something. For APK users, there should be a line in `setup.xml` that sets the value of the Preference. Later, I guess.

I've put all of this in v01.87.03. I'll go put a test build announcement on the forum.

**Comment by mougino** [comment]
When building an apk, isn't it doable with the `settings.xml` gr_accel option's `defaultValue`?

**Comment by jMarcS** [comment]
Yes, it is, but I thought you want to keep all the changes for Quick APK in `setup.xml`. We'd declare a `bool` item in `setup.xml`, say `default_hw_accel_pref`, then in `settings.xml`, the Preference item would say `android:defaultValue="@bool/default_hw_accel_pref"`, instead of `="false"`. It's one more level of indirection, but it keeps the Editor-to-APK changes in one file.

If you don't care about that, I won't change it. I have to put a note in Appendix D of the manual; it can say `settings.xml` as easily as `setup.xml`.

**Comment by mougino** [comment]
I do not care what xml file needs to be changed, yes. So we can keep it this way.

I replied on the forum that the `isHardwareAccelerated()`  condition prevents from disabling the hw accel, confirmed by  http://stackoverflow.com/questions/12119753/view-ishardwareaccelerated-is-always-false

> You should check isHardwareAccelerated() after 
> the view was attached to the window - e.g. in 
> onAttachedToWindow()!

If it's too complicated then I would suggest simply removing this second condition, and we can see what happens when hw accel is disabled at manifest level...

**Comment by jMarcS** [comment]
Released in v01.88, 2015/08/16.
