### ISSUE TITLE
Crash of BASIC! with ASCII() command

### ISSUE THREAD

**Issue by mougino** [RFO-BASIC/Basic#203]
I found a systematic hard-crash when calling `ASCII(<sexp>, <nexp>)` when `<nexp>` includes a calculation (tested on v01.88), e.g. `ASCII(e$, (i-1)*N+j)` crashes BASIC!

If the `<nexp>` is calculated first, put in an `<nvar>` and we call `ASCII()` with this `<nvar>` as second parameter, it doesn't crash.

BASIC! code to replicate the crash is on the forum:
http://rfobasic.freeforums.org/ascii-command-crash-t3943.html

(FYI, the second line of code, with the `JOIN.ALL`, is to create a fast string composed of N*N null characters, see [here] (http://rfobasic.freeforums.org/string-or-build-string-builders-t3942.html))

**Comment by jMarcS** [comment]
Wow! This has been broken since v01.83, when I added the index parameter to the ASCII and UCODE functions (August, 2014).

The field `StringConstant`, effectively a global variable, is holding the value of the string (`e$` in your example). The parser uses `StringConstant` while evaluating the index parameter, but only if expression is fairly complex. Putting parentheses in the expression makes it complex enough.

The effect is to wipe out the value copied from `e$`. The crash is a `StringIndexOutOfBoundsException`, trying to index a character of a zero-length string.

**Comment by jMarcS** [comment]
Released in v01.90, 2016/03/31.
